name: kenpotatakai
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1

  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  redux_persist: ^0.8.4
  redux_persist_flutter: ^0.8.2

  rxdart: ^0.24.0
  json_annotation: ^3.0.1
  dio: ^3.0.9

  webview_flutter: ^0.3.21
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.9.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  fonts:
  - family: Raleway
    fonts:
    - asset: fonts/Raleway-Regular.ttf
    - asset: fonts/Raleway-Bold.ttf
      weight: 700