name: kenpotatakai
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0

  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  redux_persist: ^0.8.2
  redux_persist_flutter: ^0.8.1

  rxdart: ^0.21.0
  json_annotation: ^2.0.0
  dio: ^2.1.3

  webview_flutter: ^0.3.6
  flutter_webview_plugin: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Raleway
    fonts:
    - asset: fonts/Raleway-Regular.ttf
    - asset: fonts/Raleway-Bold.ttf
      weight: 700